<testsuite failures="1" name="src/test/resources/features/UserDetails.feature" skipped="0" tests="1" time="0.666776">
  <testcase classname="src.test.resources.features.UserDetails" name="Get all test" time="0.666776">
    <failure message="UserDetails.feature:13 - path: $.date.id, actual: null, expected: 2, reason: actual json-path does not exist">Given url 'https://reqres.in/api/users/2' ................................. passed
When method GET ........................................................... passed
Then status 200 ........................................................... passed
Then print response ....................................................... passed
* def expectedOutput = read('file:src/test/resources/result/result.json') . passed
And match response == expectedOutput ...................................... passed
And match response.date.id == 2 ........................................... failed

Stack Trace:
com.intuit.karate.exception.KarateException: UserDetails.feature:13 - path: $.date.id, actual: null, expected: 2, reason: actual json-path does not exist&#13;
	at âœ½.And match response.date.id == 2 (UserDetails.feature:13)</failure>
  </testcase>
</testsuite>
